### ISSUE TITLE
NullPointerException - ring.swagger.ui

### ISSUE THREAD

**Issue by kernelp4nic** [metosin/compojure-api#127]
Hi! I'm trying to integrate compojure-api into our apps, but I'm struggling with this error:

```java
java.lang.NullPointerException
  at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
  at java.util.regex.Matcher.reset(Matcher.java:309)
  at java.util.regex.Matcher.<init>(Matcher.java:229)
  at java.util.regex.Pattern.matcher(Pattern.java:1093)
  at clojure.core$re_matcher.invoke(core.clj:4460)
  at clojure.core$re_find.invoke(core.clj:4512)
  at ring.swagger.ui$get_path.invoke(ui.clj:10)
  at ring.swagger.ui$swagger_ui$fn__29995.invoke(ui.clj:42)
  at ring.middleware.content_type$wrap_content_type$fn__29943.invoke(content_type.clj:26)
  at ring.middleware.not_modified$wrap_not_modified$fn__29966.invoke(not_modified.clj:40)
  at ring.middleware.head$wrap_head$fn__29981.invoke(head.clj:26)
  at compojure.core$routing$fn__3260.invoke(core.clj:127)
  at clojure.core$some.invoke(core.clj:2515)
  at compojure.core$routing.doInvoke(core.clj:127)
  at clojure.lang.RestFn.applyTo(RestFn.java:139)
  at clojure.core$apply.invoke(core.clj:626)
  at compojure.core$routes$fn__3264.invoke(core.clj:132)
  at clojure.lang.AFn.applyToHelper(AFn.java:154)
  at clojure.lang.AFn.applyTo(AFn.java:144)
  at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at ring.swagger.middleware$wrap_swagger_data$fn__29132.invoke(middleware.clj:33)
  at ring.middleware.http_response$wrap_http_response$fn__29113.invoke(http_response.clj:8)
  at ring.swagger.middleware$wrap_validation_errors$fn__29157.invoke(middleware.clj:68)
  at compojure.api.middleware$wrap_exceptions$fn__29181.invoke(middleware.clj:53)
  at ring.swagger.middleware$wrap_swagger_data$fn__29132.invoke(middleware.clj:33)
  at compojure.api.middleware$wrap_options$fn__29184.invoke(middleware.clj:67)
  at ring.middleware.format_params$wrap_format_params$fn__28899.invoke(format_params.clj:113)
  at ring.middleware.format_params$wrap_format_params$fn__28899.invoke(format_params.clj:113)
  at ring.middleware.format_params$wrap_format_params$fn__28899.invoke(format_params.clj:113)
  at ring.middleware.format_params$wrap_format_params$fn__28899.invoke(format_params.clj:113)
  at ring.middleware.format_params$wrap_format_params$fn__28899.invoke(format_params.clj:113)
  at ring.middleware.format_response$wrap_format_response$fn__29038.invoke(format_response.clj:175)
  at ring.middleware.keyword_params$wrap_keyword_params$fn__3446.invoke(keyword_params.clj:32)
  at ring.middleware.nested_params$wrap_nested_params$fn__3495.invoke(nested_params.clj:70)
  at ring.middleware.params$wrap_params$fn__3412.invoke(params.clj:58)
  at compojure.api.middleware$wrap_options$fn__29184.invoke(middleware.clj:67)
  at clojure.lang.AFn.applyToHelper(AFn.java:154)
  at clojure.lang.AFn.applyTo(AFn.java:144)
  at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at dosierer.webserver$start.invoke(webserver.clj:17)
  at dosierer.server.JettyWeb.start(server.clj:25)
  at dosierer.server.App.start(server.clj:71)
  at dosierer.server$_main.doInvoke(server.clj:102)
  at clojure.lang.RestFn.invoke(RestFn.java:397)
  at clojure.lang.Var.invoke(Var.java:375)
  at user$eval1216.invoke(form-init3704263792989358657.clj:1)
  at clojure.lang.Compiler.eval(Compiler.java:6703)
  at clojure.lang.Compiler.eval(Compiler.java:6693)
  at clojure.lang.Compiler.load(Compiler.java:7130)
  at clojure.lang.Compiler.loadFile(Compiler.java:7086)
  at clojure.main$load_script.invoke(main.clj:274)
  at clojure.main$init_opt.invoke(main.clj:279)
  at clojure.main$initialize.invoke(main.clj:307)
  at clojure.main$null_opt.invoke(main.clj:342)
  at clojure.main$main.doInvoke(main.clj:420)
  at clojure.lang.RestFn.invoke(RestFn.java:421)
  at clojure.lang.Var.invoke(Var.java:383)
  at clojure.lang.AFn.applyToHelper(AFn.java:156)
  at clojure.lang.Var.applyTo(Var.java:700)
  at clojure.main.main(main.java:37)
```

I'm using the example in the readme. Any thoughts?

**Comment by ikitommi** [comment]
Could you try to create an vanilla app with 

```
lein new compojure-api app
cd app
lein ring server
```

, check that it works and see what you are doing differently (deps, versions, routes)?

**Comment by kernelp4nic** [comment]
Ok that works as expected. And my example also works fine if I run it with `lein ring plugin`.
My code is calling `ring.adapter.jetty/run-jetty` wrong.

Sorry about the noise!
Thanks!

**Comment by blak3mill3r** [comment]
For posterity, in case anyone runs into this and does not wish to start from the `lein` template:

I ran into this because I was passing the result of `compojure.api.sweet/api` to `system.components.endpoint/new-endpoint`, which is wrong. The latter expects a function that returns routes, not the routes themselves. Makes sense.
