### ISSUE TITLE
Middleware and anonymous functions in version 1.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by rcanepa** [metosin/compojure-api#208]
Hey,

I recently updated my code to use the new version of compojure-api. The process was very simple but I couldn't make the `middleware` macro work with an anonymous function as an argument as it is specified here: https://github.com/metosin/compojure-api/wiki/Migration-Guide-to-1.0.0#middleware

Next, two pieces of code. The first works and the second does not.
````
...
 (context "/api/v1" request
              :tags ["api"]

              (context "/actions" []
                        :tags ["actions"]

                        (middleware [cors-mw
                                     [wrap-set-auth-user auth-tokens] ; This works
                                     wrap-authentication]

                                     (GET "/" []
                                           :return [actions/Action]
                                           :summary "Retrieve all actions."
                                           (http/ok (actions/fetch-actions db)))
...
````

````
...
 (context "/api/v1" request
              :tags ["api"]

              (context "/actions" []
                        :tags ["actions"]

                        (middleware [cors-mw
                                     #(wrap-set-auth-user % auth-tokens) ; This doesn't work
                                     wrap-authentication]

                                     (GET "/" []
                                           :return [actions/Action]
                                           :summary "Retrieve all actions."
                                           (http/ok (actions/fetch-actions db)))
...
````
That code throws this:
````
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.AssertionError: Assert failed: Middleware vector must only contain
a) fully configured middleware (function) or
b) vectors containing middleware function and additional parameters for it.
(and (vector? middleware) (every? (fn* [p1__15876#] (or (and (vector? p1__15876#) (ifn? (first p1__15876#))) (ifn? p1__15876#))) middleware)), compiling:(scv2backend/endpoint/api.clj:152:25)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
...
````

**Comment by Deraen** [comment]
Okay, I see the problem. Middlewares are asserted in macro expansion time so the assertion will see the code instead of functions. It's easy to fix `middleware` macro but fixing `:middleware` requires #207
