### ISSUE TITLE
StackOverFlowException when using Compojure API with swagger spec

### ISSUE THREAD

**Issue by weixunter** [metosin/compojure-api#291]
Packaged my service into a jar with 
$lein ring uberjar
When executing the jar
$java -jar example-standalone.jar
Got some StackOverFlowError at compile time?

The stack trace is long, so I will condensed it and just point out a few standout at and cause lines:

```
Exception in thread "main" java.lang.StackOverflowError, compiling:(flatland/useful/experimental/delegate.clj:54:27)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at flatland.ordered.map$eval5034$loading__5569__auto____5035.invoke(map.clj:1)
	at clj_yaml.core$eval5028$loading__5569__auto____5029.invoke(core.clj:1)
	at ring.middleware.format_params$eval4157$loading__5569__auto____4158.invoke(format_params.clj:1)
	at compojure.api.middleware$eval3651$loading__5569__auto____3652.invoke(middleware.clj:1)
	at compojure.api.meta$eval3629$loading__5569__auto____3630.invoke(meta.clj:1)
	at compojure.api.core$eval3623$loading__5569__auto____3624.invoke(core.clj:1)
	at compojure.api.sweet$eval3617$loading__5569__auto____3618.invoke(sweet.clj:1)
	at predictions_api.endpoints$eval3611$loading__5569__auto____3612.invoke(endpoints.clj:1)
	at ring.server.leiningen$load_var.invokeStatic(leiningen.clj:7)
	at predictions_api.endpoints.main$_main.invokeStatic(main.clj:1)
Caused by: java.lang.StackOverflowError
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4250)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
	at java.util.regex.Pattern$Start.match(Pattern.java:3461)
	at java.util.regex.Matcher.search(Matcher.java:1248)
	at java.util.regex.Matcher.find(Matcher.java:664)
	at java.util.Formatter.parse(Formatter.java:2549)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
```
Using lein ring server work flawlessly.
$lein ring server

**Comment by weixunter** [comment]
also get the same exception  with the following cause:
```
Caused by: java.lang.StackOverflowError
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3797)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
	at java.util.regex.Pattern$BranchConn.match(Pattern.java:4568)
	at java.util.regex.Pattern$GroupTail.match(Pattern.java:4717)
	at java.util.regex.Pattern$Curly.match0(Pattern.java:4279)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4234)
	at java.util.regex.Pattern$GroupHead.match(Pattern.java:4658)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4604)
	at java.util.regex.Pattern$Branch.match(Pattern.java:4602)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3798)
	at java.util.regex.Pattern$Start.match(Pattern.java:3461)
	at java.util.regex.Matcher.search(Matcher.java:1248)
	at java.util.regex.Matcher.find(Matcher.java:664)
	at java.util.Formatter.parse(Formatter.java:2549)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at clojure.lang.Compiler.errorMsg(Compiler.java:6886)
	at clojure.lang.Compiler$CompilerException.<init>(Compiler.java:6700)
	at clojure.lang.Compiler.analyze(Compiler.java:6688)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6269)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
```
and
```
Caused by: java.lang.StackOverflowError
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$_LT___inliner__4483.invokeStatic(core.clj:881)
	at clojure.core$_LT___inliner__4483.invoke(core.clj:881)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6863)
```

**Comment by weixunter** [comment]
As well as 
```
Exception in thread "main" java.lang.StackOverflowError, compiling:(slingshot/support.clj:142:32)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6863)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2792)
	at slingshot.slingshot$eval3669$loading__5569__auto____3670.invoke(slingshot.clj:1)
	at ring.util.http_response$eval3663$loading__5569__auto____3664.invoke(http_response.clj:1)
	at compojure.api.exception$eval3657$loading__5569__auto____3658.invoke(exception.clj:1)
	at compojure.api.middleware$eval3651$loading__5569__auto____3652.invoke(middleware.clj:1)
	at compojure.api.meta$eval3629$loading__5569__auto____3630.invoke(meta.clj:1)
	at compojure.api.core$eval3623$loading__5569__auto____3624.invoke(core.clj:1)
	at compojure.api.sweet$eval3617$loading__5569__auto____3618.invoke(sweet.clj:1)
	at predictions_api.endpoints$eval3611$loading__5569__auto____3612.invoke(endpoints.clj:1)
	at ring.server.leiningen$load_var.invokeStatic(leiningen.clj:7)
	at predictions_api.endpoints.main$_main.invokeStatic(main.clj:1)
	at predictions_api.endpoints.main$_main.invoke(main.clj:1)
	at predictions_api.endpoints.main.main(Unknown Source)
Caused by: java.lang.StackOverflowError
	at clojure.lang.DynamicClassLoader.findInMemoryClass(DynamicClassLoader.java:52)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:75)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
```

**Comment by weixunter** [comment]
endpoints.clj snippet:
```
(ns predictions-api.endpoints
  (:require [compojure.api.sweet :refer :all]
            [com.stuartsierra.component :as component]
            [api.config.component-system-map :as sys-map]
            [api.contract.schema :refer :all]
            [api.handlers.handler-health-check :as handler-health-check]
            [ring.middleware.ssl :refer [wrap-ssl-redirect]]
            [schema.core :as s]
            [ring.middleware.defaults :refer :all]))

(defapi app-routes
  {:swagger
   {:ui      "/"
    :spec    "/swagger.json"
    :data    {:info {:title "test"}
              :tags [{:name "healthcheck", :description "API Health Check"}
                     {:name "Sum", :description "Sum"}]}}}

(context "/health/check" []
  :tags ["HealthCheck"]
  (GET "/" []
    :description "This endpoint check the health status of the API"
    :summary "return health status"
    :responses {200 {:description "OK"}}
    (handler-health-check/get-route-health-check)))

(context "/v1/api/" [a b]
  :tags ["Sum"]
  (GET "/" []
    :summary "test"
    :path-params [a :- (describe s/Str "a")
                  b :- (describe s/Str "b")]
    :responses {200 {:schema Sum :description "OK"}
                400 {:description "Bad request"}
                404 {:description "Not found"}
                500 {:description "Internal server error encountered"}
                504 {:description "Timeout, please try again"}}
    (+ a b))))

(def app
  (-> app-routes
      (wrap-ssl-redirect)))

(defn init []
  (log/info "service is beginning its initialization process")
  (app-config/init-properties)
  (reset! component-system-map (component/start (sys-map/system))))

(defn destroy []
  (swap! component-system-map component/stop)
  (log/info "service is shut down successfully."))
```

project.clj snippet:
```
(defproject test 0.0.1
  :min-lein-version "2.5.3"
  :resource-paths ["resources/dynamic-properties" "resources"]
  :dependencies [[metosin/compojure-api                                     "1.1.10"]
                 [metosin/ring-http-response                                "0.8.1"]
                 [org.clojure/clojure                                       "1.8.0"]
                 [ring/ring-codec                                           "1.0.1"]
                 [ring/ring-core                                            "1.5.1"]
                 [ring/ring-defaults                                        "0.2.0"]
                 [ring/ring-json                                            "0.4.0"]
                 [ring/ring-ssl                                             "0.2.1"]
                 [slingshot                                                 "0.12.2"]]
  :plugins [[lein-ring "0.11.0"]]
  :pedantic? :abort
  :ring {:init         api.endpoints/init                
         :destroy      api.endpoints/destroy
         :handler      api.endpoints/app :port 8080      
         :ssl?         true
         :ssl-port     8443
         :keystore     "key.jks"
         :key-password "pass"})
```

**Comment by weixunter** [comment]
I have schema definition that is something like this: 
(s/if cond? true false)
Would it has cause it ???
```
(ns api.contract.schema
  (:require [schema.core :as s]
            [compojure.api.sweet :refer :all]))

(s/defschema SomeSchema
  {:parameters {:foo      (describe (s/if nil? s/Any s/Uuid) "if null any type is good, else uuid")
                :bar               (describe s/Uuid "The organization id provided as part of the query")})
```

**Comment by weixunter** [comment]
Found out what was wrong. In the server the jvm options is set to too low value -Xss256k increasing it to -Xss512k works. 

Closing this issue.

**Comment by weixunter** [comment]
Closing this issue.
