### ISSUE TITLE
Support for schemas as map values

### ISSUE THREAD

**Issue by acrao** [metosin/compojure-api#53]
I'm having some difficulty integrating a schema map using ```maybe``` in the map value. Here is the schema definition for the data that my API returns : 

    (def Boundary
      {:type (enum "MultiPolygon" "Polygon" "MultiPoint" "Point")
       :coordinates [Any]}) 

    (def ReturnValue
      {:boundary (maybe Boundary) ;; can be of type Boundary or nil. In either case, 
                                                       ;; the key should always exist
       .....}

Here is the exception I'm running into when starting my server :

````stacktrace
java.lang.IllegalArgumentException: error converting to json schema [:boundary (maybe {:type (enum "Point" "Polygon" "MultiPolygon" "MultiPoint"), :coordinates [Any]})]
	at ring.swagger.json_schema$properties$iter__10215__10219$fn__10220$fn__10228.invoke(json_schema.clj:117)
	at ring.swagger.json_schema$properties$iter__10215__10219$fn__10220.invoke(json_schema.clj:113)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:598)
......

Caused by: java.lang.IllegalArgumentException: don't know how to create json-type of: {:type (enum "Point" "Polygon" "MultiPolygon" "MultiPoint"), :coordinates [Any]}
	at ring.swagger.json_schema$eval10210$fn__10211.invoke(json_schema.clj:95)
	at clojure.lang.MultiFn.invoke(MultiFn.java:227)
	at ring.swagger.json_schema$__GT_json.doInvoke(json_schema.clj:47)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at ring.swagger.json_schema$eval10190$fn__10191.invoke(json_schema.clj:86)
	at clojure.lang.MultiFn.invoke(MultiFn.java:227)
	at ring.swagger.json_schema$__GT_json.doInvoke(json_schema.clj:47)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at ring.swagger.json_schema$properties$iter__10215__10219$fn__10220$fn__10228.invoke(json_schema.clj:113)
	... 94 more
````

I'm using ```[metosin/compojure-api "0.16.2"]```. I'm not quite sure what I'm missing here. Any pointers as to how I can get around this? Do I need to define a custom ```json-schema```?

**Comment by ikitommi** [comment]
Fixed now, by @Deraen.

See https://github.com/metosin/compojure-api/blob/master/test/compojure/api/core_integration_test.clj#L535-L566

Will wrap the sub-walker as a separate lib so that it can be extended easier.
